[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "plotly>=6.3.0",
    "polars>=1.32.3",
    "streamlit>=1.47.1",
]
