[project]
name = "models"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "litserve>=0.2.12",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.10.5",
    "pydantic-settings>=2.9.1",
    "numpy>=2.3.0",
    "sentence-transformers>=4.1.0",
]
